https/tls_config_test.go, https/users.go
https://tools.ietf.org/html/rfc7235#section-3.1
> If the request included authentication credentials, then the 401
> response indicates that authorization has been refused for those
> credentials.
cc @SuperQ 
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Return 401 when bad credentials are passed

web/cache.go, web/cache_test.go, web/tls_config.go, web/tls_config_test.go, web/users.go, web/users_test.go
In order to improve the response time with basic authentication, cache
the results of bcrypt in memory.
This is a draft to see if that approach would be acceptable.
The code is coming from Caddy, and I have fullfiled the attribution
required by Apache-2 by adding the copyright to our headers:
https://github.com/caddyserver/caddy/commit/9a7756c6e4b4ddb945bede3ddb2dfbf241208915
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Cache basic authentications

web/cache.go
If you ended up with 1000 users in your web config, we would have
pre-allocated a map with 1000 entries. The maximum size of the map is
currently hardcoded to 100, so 900 of the preallocations would never be
used.
This limits the initial pre-allocation to 10% of the map size, which is
at this moment 10.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Limit basicauth cache size

web/users.go, web/users_test.go
This commit makes sure that the timing is similar when a user exists or
does not exist.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Prevent user enumeration

web/testdata/tls_config_noAuth.requireanyclientcert.good.yml, web/tls_config.go, web/tls_config_test.go
`RequireAnyClientCert` is the actual name, not `RequireClientCert`
Fixes prometheus/prometheus#9066
=> Fix ClientAuth type typo

.circleci/config.yml
After the merge of https://github.com/prometheus/exporter-toolkit/pull/64, golangci-lint is run a GitHub Action instead of CircleCI. Now, the `lint` job doesn't do anything: https://app.circleci.com/pipelines/github/prometheus/exporter-toolkit/155/workflows/9a5f9807-a960-49a6-a148-d048b383735d/jobs/419/parallel-runs/0/steps/0-102.
=> Remove unused `lint` job

web/tls_config.go
Hi, maintainers (@SuperQ and @roidelapluie).
This PR fixes an issue in exporter-toolkit where it always overrides the `NextProtos` field in `TLSConfig` for every request and results in HTTP/1.1 even though HTTP 2 is enabled by default. The current implementation around `GetConfigForClient` always overrides `NextProtos` field that is internally set to `[]string{"h2", "http/1.1"}` when initializing server in `net/http`:
https://github.com/golang/go/blob/go1.17.3/src/net/http/h2_bundle.go#L6817-L6822
---
To simply reproduce this issue, use this snippet of code:
```go
package main
import (
"fmt"
"net/http"
"os"
"github.com/go-kit/log"
"github.com/prometheus/exporter-toolkit/web"
)
func main() {
handler := http.NewServeMux()
handler.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) …
```
=> Fix a bug where HTTP 2 connections were not working

.circleci/config.yml, go.mod
* Update tests for Go 1.17/1.18.
* `go mod tidy -go=1.17`
Signed-off-by: SuperQ <superq@gmail.com>
=> Update for Go 1.17

web/tls_config.go, web/tls_config_test.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
=> Remove ioutil

go.mod, go.sum
For CVE-2022-27191, the golang.org/x/crypto/ssh package before 0.0.0-20220314234659-1baeb1ce4c0b for Go allows an attacker to crash a server in certain circumstances involving AddHostKey.
Although the module golang.org/x/crypto/ssh is not used in the project, it still be scanned and reported for every raw vulnerability scanner. Maybe we could just upgrade it to safe version to avoid the unnecessary discussion like [this](https://github.com/prometheus/exporter-toolkit/issues/85)
=> Bump golang.org/x/crypto to v0.0.0-20220315160706-3147a52a75dd

go.mod, go.sum, web/tls_config.go
Since https://github.com/pkg/errors is archived by the owner, let's replace is with stdlib features.
=> web: Replace pkg/errors with stdlib errors

web/tls_config.go
By exporting the type, it becomes possible to construct a value in code outside this package, and pass in to the toolkit.
Fixes #109
=> Allow TLS parameters to be set in code

docs/web-configuration.md
Addresses [this issue](https://github.com/prometheus/prometheus/issues/10852) from the Prometheus repo for the exporter-toolkit repo.
Signed-off-by: Alex Gavin <a_gavin@icloud.com>
=> docs: clarify supported tls cipher suites

docs/web-configuration.md
May refer to https://github.com/prometheus/exporter-toolkit/blob/14464f8d9bad4970fb2bbb16d64af22075aa4ec9/web/handler.go#L35
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> docs: correct the accepted value for X-XSS-Protection header

web/tls_config.go
Rename `Struct` to `Config` to make the struct naming less redundant.
Signed-off-by: SuperQ <superq@gmail.com>
=> Rename department of redundancy

.golangci.yml, web/tls_config_test.go
Replace deprecated golint with revive
Add goimports and misspell linters as they are used in https://github.com/prometheus/prometheus/blob/main/.golangci.yml
=> Update golangci linters

go.mod, go.sum, web/kingpinflag/flag.go
Upstream changed package name, see:
https://github.com/alecthomas/kingpin#overview
=> go.mod: Update gopkg.in/alecthomas/kingpin.v2 to github.com/alecthomas/kingpin/v2

web/tls_config.go
Noticed this when working with https://github.com/Lusitaniae/apache_exporter
If you don't provide a boolean value for WebSystemdSocket (default false) calling ListenAndServe causes the application to SigSegv. This checks if it is nil before evaluating the boolean value.
=> Fix Nil pointer references for WebSystemdSocket

web/landing_page.go
Set the landing page Content-Type header to HTML.
=> Add a Content-Type header to the landing page

web/kingpinflag/flag.go
The help message generated by the toolkit leaves users with no hints about what to put in the `web.config.file`. Because this toolkit is designed to be embedded in other projects, it would be non-obvious for a user to know to come to this repo and examine the docs folder.
This PR assumes that `/docs/web-configuration.md` is intended to be a stable URL and directs users to it so they know how to populate the file.
Tagging @SuperQ and @roidelapluie per `CONTRIBUTING.md`
=> Refer user to doco from help message

web/landing_page.css, web/landing_page.go, web/landing_page.html
Add configuration to the landing page generator to allow a POST form.
* Reduce header font size.
=> Add a POST form to the landing page

web/landing_page.css, web/landing_page.go, web/landing_page.html
Allow generic additional HTML or CSS to be added to the landing page output.
=> Add generic customization to landing page

web/kingpinflag/flag.go
Removes experimental from the CLI flag, as it has been there for 3 years now.
=> Remove experimental in CLI

web/tls_config_go118_test.go, web/tls_config_go121_test.go, web/tls_config_test.go
Go 1.21 introduced more granular / specific error strings for certain "bad certificate" scenarios[1]. As such, we need to split these tests and conditionally compile based on build tags.
Fixes: #171, #187
[1]: https://github.com/golang/go/commit/62a994837a57a7d0c58bb364b580a389488446c9
=> Split TLS client tests to handle Go 1.21+ error strings

web/landing_page.css, web/landing_page.html
Make it easier for users to fetch and download pprof data for debugging.
* Add a link to https://pprof.me for easy sharing.
=> Add pprof links to landing page

web/kingpinflag/flag.go
=> Support kingpin.CmdClause as argument

.golangci.yml, go.mod, go.sum, web/handler.go, web/tls_config.go, web/tls_config_test.go
Switch to log/slog to align with https://github.com/prometheus/common/pull/677
=> Switch to slog

web/landing_page.go
This would fix #241 we ran into this issue when some of our automated tests fully believed that node exporter was leaking a linux home directory as it was returning HTTP 200 on requests like .bash_history
=> Only display landing page on /

web/landing_page.go, web/landing_page.html
This new parameter will allow for serving the landing page when using --web.external-url as an argument with many exporters. 
I added this as it is needed for this pull request: https://github.com/prometheus/snmp_exporter/pull/1335
So in practice it will look something like this:
```go
landingConfig := web.LandingConfig{
// config stuff goes here ...
}
// new parameter
landingPage, err := web.NewLandingPage(landingConfig, *routePrefix != "")
if err != nil {
logger.Error("Error creating landing page", "err", err)
os.Exit(1)
}
http.Handle(*routePrefix, landingPage)
```
=> Serve behind route prefix

web/landing_page.html
Adding rel="noopener noreferrer" to external links that use target="_blank" to prevent potential reverse tabnabbing attacks. This security enhancement blocks malicious websites opened in new tabs from manipulating the original page context.
=> Add security attributes to external links to prevent reverse tabnabbing

web/landing_page.go
Fix for #296 
Trim off a leading slash on the Action button URL if present
=> Trim leading slash on Action button URL

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile.common
Bump golangci-lint to v2.0.2 (aligned with prometheus actual version)
=> chore: bump golangci-lint to v2.0.2

web/tls_config_test.go
looks like https://github.com/prometheus/exporter-toolkit/pull/337 caused a test failure due to a regexp, this should fix it.
=> fix: Fix test
